apiVersion: v1
kind: Service
metadata:
  name: htech-finance-app
  labels:
    app: htech-finance-app
spec:
  type: LoadBalancer
  selector:
    app: htech-finance-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
